services:
  app:
    image: app-image
    container_name: testsite
    build: .
    ports:
      - 8000:5000
    volumes:
      - ./app:/app
    env_file:
      - .env-container
    networks:
      - testsite-network

  db:
    env_file:
      - .env-container
    container_name: mysql
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - testsite-network

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.7.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - testsite-network

  worker:
    image: app-image
    entrypoint:
      - rq
    command:  worker -u redis://redis:6379/0 testsite-tasks
    networks:
      - testsite-network

  dashboard:
    image: rq-dashboard
    build:
      context: .
      dockerfile: rq-dashboard/Dockerfile
    ports:
      - 9181:9181
    networks:
      - testsite-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    env_file:
      - .env-container
    volumes:
      - redis_data:/data
    networks:
      - testsite-network

volumes:
  db_data:
    driver: local
  es_data:
    driver: local
  redis_data:
    driver: local


networks:
  testsite-network:


