"""empty message

Revision ID: 88150f0d88f4
Revises: de73cb5f06bb
Create Date: 2024-06-22 20:25:36.730588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88150f0d88f4'
down_revision = 'de73cb5f06bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('psw_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('psw_hash',
               existing_type=sa.Text(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
