"""empty message

Revision ID: de73cb5f06bb
Revises: 1bd09fc7a1dc
Create Date: 2024-06-09 21:03:23.712100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de73cb5f06bb'
down_revision = '1bd09fc7a1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=140),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(length=140),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
